-- Self-service onboarding applications for new circles (reviewed/approved by an
-- admin, then provisioned into a real Circle).
CREATE TABLE `CircleSignup` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `circleName` VARCHAR(191) NULL,
  `phoneEnc` TEXT NOT NULL,
  `phoneHash` VARCHAR(191) NOT NULL,
  `phoneMask` VARCHAR(191) NOT NULL,
  `termsVersion` VARCHAR(191) NOT NULL,
  `termsAcceptedAt` DATETIME(3) NOT NULL,
  `termsIp` VARCHAR(191) NULL,
  `termsUserAgent` TEXT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'pending_review',
  `reviewToken` VARCHAR(191) NOT NULL,
  `resumeToken` VARCHAR(191) NOT NULL,
  `waNumber` VARCHAR(191) NULL,
  `emailAddress` VARCHAR(191) NULL,
  `emailHost` VARCHAR(191) NULL,
  `emailPort` INTEGER NULL,
  `emailEncCred` TEXT NULL,
  `circleId` VARCHAR(191) NULL,
  `reviewedAt` DATETIME(3) NULL,
  `reviewedBy` VARCHAR(191) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `CircleSignup_reviewToken_key` (`reviewToken`),
  UNIQUE INDEX `CircleSignup_resumeToken_key` (`resumeToken`),
  INDEX `CircleSignup_status_idx` (`status`),
  INDEX `CircleSignup_email_idx` (`email`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
